# Generated by Django 5.1.8 on 2026-06-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='image',
        ),
        migrations.CreateModel(
            name='SupportTicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='support_tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
