# Generated by Django 5.1.8 on 2026-06-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_supportticket_admin_typing_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmessage',
            name='delivery_status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('SEEN', 'Seen')], default='SENT', max_length=15),
        ),
    ]
