# Generated by Django 5.1.8 on 2026-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_supportticketmessage_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmessage',
            name='is_admin_reply',
            field=models.BooleanField(default=False),
        ),
    ]
