# Generated by Django 5.1.8 on 2026-06-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_supportticketmessage_is_admin_reply'),
        ('wholesale', '0008_wholesalenotification_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='wholesale_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='wholesale.wholesaleuser'),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='wholesale_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='wholesale.wholesaleuser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('promo', 'Promotional Offer'), ('price_change', 'Price Change'), ('leftover_pack', 'Leftover Pack Available'), ('ticket_reply', 'Support Ticket Reply'), ('admin_ticket_reply', 'Admin Ticket Reply'), ('admin_alert', 'Admin Alert'), ('out_of_stock', 'Out of Stock Alert'), ('wholesale_pending', 'Wholesale Pending Approval')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
