# Generated by Django 5.1.8 on 2026-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sitesettings_image_alter_sitesettings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
