# Generated by Django 5.1.8 on 2026-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_freeshippingrule_applicable_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat discount amount (used when discount_type=FLAT)', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage'), ('FLAT', 'Flat Amount')], default='PERCENT', max_length=10),
        ),
    ]
