# Generated by Django 5.1.8 on 2026-06-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_shippingmethod_is_wholesale_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_hidden_from_customer',
            field=models.BooleanField(default=False, help_text="If True, order is hidden from the customer's history."),
        ),
    ]
