# Generated by Django 5.1.8 on 2026-06-25 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_is_hidden_from_customer'),
        ('stores', '0006_leftoverpack_shipping_category_leftoverpack_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_at_store',
            field=models.ForeignKey(blank=True, help_text='The store from which this order was processed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='The staff member who confirmed/processed this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
