# Generated by Django 5.1.8 on 2026-06-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_offer_products_offeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tax percentage for this product (e.g., 5.00 for 5%)', max_digits=5),
        ),
    ]
