# Generated by Django 5.1.8 on 2026-06-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='affiliate_commission_rate',
        ),
    ]
