# Generated by Django 5.1.8 on 2026-06-25 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_affiliate_commission_rate'),
        ('stores', '0006_leftoverpack_shipping_category_leftoverpack_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Physical fulfillment store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stores.store'),
        ),
    ]
