# Generated by Django 5.1.8 on 2026-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_store'),
        ('stores', '0006_leftoverpack_shipping_category_leftoverpack_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, help_text='Physical fulfillment stores', related_name='products', to='stores.store'),
        ),
    ]
