# Generated by Django 5.1.8 on 2026-06-25 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staffprofile_can_create_products_and_more'),
        ('stores', '0006_leftoverpack_shipping_category_leftoverpack_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_all_stores', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_staff', models.ManyToManyField(blank=True, related_name='announcements', to='staff.staffprofile')),
                ('target_stores', models.ManyToManyField(blank=True, related_name='announcements', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
