# Generated by Django 5.1.8 on 2026-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_wholesalebenefit_wholesalecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleuser',
            name='serial_number',
        ),
    ]
