# Generated by Django 5.1.8 on 2026-06-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0006_alter_wholesaleuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('store', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('purchase', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('purchase_note', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='wholesale.wholesaleuser')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
