# Generated by Django 5.1.8 on 2026-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0007_wholesaledailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalenotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
