# Generated by Django 5.1.8 on 2026-07-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0009_force_remove_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleuser',
            name='serial_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
