# Generated by Django 5.1.8 on 2026-07-19 09:29

from django.db import migrations


def fix_id_sequence(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            try:
                # Attempt to add the IDENTITY property to the ID column
                cursor.execute('ALTER TABLE "wholesale_wholesaleuser" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;')
            except Exception:
                # If it fails (e.g., already an identity column), ignore the error
                pass
            
            try:
                # Sync the sequence to the maximum ID to avoid duplicate key errors
                cursor.execute('SELECT setval(pg_get_serial_sequence(\'"wholesale_wholesaleuser"\', \'id\'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "wholesale_wholesaleuser";')
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0010_wholesaleuser_serial_number'),
    ]

    operations = [
        migrations.RunPython(fix_id_sequence, reverse_code=migrations.RunPython.noop),
    ]
