from django.db import migrations, transaction


def fix_id_sequence(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            try:
                # Use a savepoint so a failure doesn't abort the entire migration transaction
                with transaction.atomic():
                    # Attempt to add the IDENTITY property to the ID column
                    cursor.execute('ALTER TABLE "wholesale_wholesaleuser" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;')
            except Exception:
                # If it fails (e.g., syntax error on older PG, or already an identity), ignore
                pass
            
            try:
                with transaction.atomic():
                    # If it wasn't an identity column but a SERIAL sequence, we can try to link the sequence directly if IDENTITY failed
                    # In many cases, it's just the sequence that got detached.
                    # First, let's make sure the sequence exists
                    cursor.execute('CREATE SEQUENCE IF NOT EXISTS wholesale_wholesaleuser_id_seq;')
                    cursor.execute('ALTER TABLE "wholesale_wholesaleuser" ALTER COLUMN "id" SET DEFAULT nextval(\'wholesale_wholesaleuser_id_seq\');')
                    cursor.execute('ALTER SEQUENCE wholesale_wholesaleuser_id_seq OWNED BY "wholesale_wholesaleuser"."id";')
            except Exception:
                pass

            try:
                with transaction.atomic():
                    # Sync the sequence to the maximum ID to avoid duplicate key errors
                    cursor.execute('SELECT setval(pg_get_serial_sequence(\'"wholesale_wholesaleuser"\', \'id\'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "wholesale_wholesaleuser";')
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0010_wholesaleuser_serial_number'),
    ]

    operations = [
        migrations.RunPython(fix_id_sequence, reverse_code=migrations.RunPython.noop),
    ]
