# Generated by Django 5.1.8 on 2026-07-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_DELETED', 'Product Deleted'), ('VENDOR_REGISTERED', 'Vendor Registered'), ('TICKET_CREATED', 'Ticket Created'), ('ORDER_PLACED', 'Order Placed'), ('DAY_OFF_REQUEST', 'Day Off Request'), ('TASK_COMPLETED', 'Task Completed')], db_index=True, max_length=25),
        ),
    ]
