# Generated by Django 5.1.8 on 2026-07-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendorticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vendor Ticket', 'verbose_name_plural': 'Vendor Tickets'},
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vendorticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
